#!/bin/bash

WORKING_DIR=$1
INTEGRATION=$2

INTEGRATION_DIR="$WORKING_DIR/exporters/$INTEGRATION"
TEMPLATES_DIR="$WORKING_DIR/nri-config-generator/templates/"

INTEGRATION_TEMPLATE_FILE="$INTEGRATION.json.tmpl"
INTEGRATION_TEMPLATE_NAME="nri-$INTEGRATION_TEMPLATE_FILE"
INTEGRATION_TEMPLATE_PATH="$INTEGRATION_DIR/$INTEGRATION_TEMPLATE_FILE"

PROMETHEUS_TEMPLATE_FILE="$INTEGRATION.prometheus.json.tmpl"
PROMETHEUS_TEMPLATE_NAME="nri-$PROMETHEUS_TEMPLATE_FILE"
PROMETHEUS_TEMPLATE_PATH="$INTEGRATION_DIR/$PROMETHEUS_TEMPLATE_FILE"

DEFAULT_PROMETHEUS_TEMPLATE_PATH="$TEMPLATES_DIR/default/config.json.tmpl"

cp $INTEGRATION_TEMPLATE_PATH "$TEMPLATES_DIR/$INTEGRATION_TEMPLATE_NAME"

if [ -f $PROMETHEUS_TEMPLATE_PATH ]; then
    echo "Using prometheus template $PROMETHEUS_TEMPLATE_PATH"
    cp $PROMETHEUS_TEMPLATE_PATH "$TEMPLATES_DIR/$PROMETHEUS_TEMPLATE_NAME"
else
    echo "Using Default prometheus template"
    cp $DEFAULT_PROMETHEUS_TEMPLATE_PATH "$WORKING_DIR/nri-config-generator/templates/$PROMETHEUS_TEMPLATE_NAME"
fi
