name: test Bash on Windows
on:
  workflow_dispatch:
  pull_request:  # I have to add pr to the test because `workflow_dispatch` is not going to be available until I merge it to `main`/`master`/default branch
    branches: [ main, master ]

jobs:
  gitbash-on-windows:
    runs-on: windows-latest
    steps:
      - name:  "Shell: gitbash.exe"
        shell: 'C:\Program Files\Git\bin\bash.exe --noprofile --norc -e -o pipefail {0}'
        run: |
          which make
          
          echo $PATH
          
          SAVEIFS="$IFS"
          export IFS=:
          for P in $PATH; do
            echo $P
            ls -lha $P || echo Ignoring error here
            echo
          done

  msys2bash-on-windows:
    runs-on: windows-latest
    steps:
      - name:  "Shell: msys2bash.cmd"
        shell: 'C:\msys64\usr\bin\bash.exe --noprofile --norc -e -o pipefail {0}'
        run: |
          which make
          
          echo $PATH
          
          SAVEIFS="$IFS"
          export IFS=:
          for P in $PATH; do
            echo $P
            ls -lha $P || echo Ignoring error here
            echo
          done

  wslbash-on-windows:
    runs-on: windows-latest
    steps:
      - name:  "Shell: wslbash.exe"
        shell: 'C:\Windows\System32\bash.exe --noprofile --norc -e -o pipefail {0}'
        run: |
          which make
          
          echo $PATH
          
          SAVEIFS="$IFS"
          export IFS=:
          for P in $PATH; do
            echo $P
            ls -lha $P || echo Ignoring error here
            echo
          done

  simplybash-on-windows:
    runs-on: windows-latest
    steps:
      - name:  "Shell: bash"
        shell: bash
        run: |
          which make
          
          echo $PATH
          
          SAVEIFS="$IFS"
          export IFS=:
          for P in $PATH; do
            echo $P
            ls -lha $P || echo Ignoring error here
            echo
          done
